"""empty message

Revision ID: 13d85f7e78c7
Revises: c08b95f6272e
Create Date: 2021-09-21 16:16:59.026449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d85f7e78c7'
down_revision = 'c08b95f6272e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'bookings', 'spots', ['spotId'], ['id'])
    op.create_foreign_key(None, 'bookings', 'users', ['userId'], ['id'])
    op.create_foreign_key(None, 'images', 'spots', ['spotId'], ['id'])
    op.create_foreign_key(None, 'reviews', 'spots', ['spotId'], ['id'])
    op.create_foreign_key(None, 'reviews', 'users', ['userId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_table('spots')
    # ### end Alembic commands ###
