"""empty message

Revision ID: e1726f3b36bf
Revises: 13d85f7e78c7
Create Date: 2021-09-22 08:41:18.089696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1726f3b36bf'
down_revision = 'c08b95f6272e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review', sa.Text(), nullable=False))
    op.drop_column('reviews', 'endDate')
    op.drop_column('reviews', 'startDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('startDate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('endDate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('reviews', 'review')
    # ### end Alembic commands ###
